version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:11
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume:
