version: '3'
services:
  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - '6379:6379'
    command: redis-server --requirepass redispass
    restart: always
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: '10m'